# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).

# create 5 posts
posts = Post.create([
  {title: 'How Scope Effects Functions',
  author: 'Eric Lombardo',
  published: '01-05-2021',
  content: 'Creative marketing channels sales client partnership investor disruptive user experience metrics graphical user interface ramen. Network effects focus market creative assets direct mailing pivot holy grail deployment social proof iteration churn rate partnership. Conversion interaction design niche market. Series A financing business model canvas investor creative channels iteration supply chain bootstrapping infographic A/B testing partner network iPad value proposition innovator. Business plan entrepreneur gen-z social proof metrics. Strategy learning curve pitch. Learning curve iPhone niche market lean startup value proposition low hanging fruit funding entrepreneur stock. Value proposition burn rate responsive web design. Partnership strategy seed money validation alpha ownership non-disclosure agreement deployment. Graphical user interface research & development first mover advantage scrum project.

  Social proof churn rate business plan infographic MVP market. Alpha infographic stock termsheet scrum project release android learning curve iPad gen-z stealth. Channels holy grail leverage influencer android buyer disruptive iteration. Paradigm shift equity gamification sales. A/B testing analytics startup customer return on investment research & development. Lean startup technology return on investment hackathon social media interaction design freemium buyer seed round leverage client pitch facebook. Growth hacking virality early adopters MVP alpha. Network effects user experience freemium validation prototype startup incubator monetization buyer value proposition. Responsive web design value proposition bootstrapping stock startup influencer conversion hackathon accelerator. Marketing first mover advantage product management startup.
  
  Buzz business plan stock monetization ramen founders analytics creative vesting period. Beta burn rate product management hypotheses crowdsource startup technology value proposition angel investor focus series A financing marketing launch party direct mailing. Social media deployment client release strategy. Success churn rate niche market low hanging fruit graphical user interface innovator crowdfunding termsheet research & development android paradigm shift influencer pitch lean startup. Social media graphical user interface social proof infrastructure low hanging fruit hypotheses customer. Freemium crowdsource mass market ecosystem. Supply chain user experience paradigm shift crowdsource growth hacking business model canvas bandwidth pitch vesting period. Success seed money first mover advantage metrics hypotheses. Business-to-business stealth beta incubator gamification seed round partner network. MVP traction launch party virality release seed round monetization infographic rockstar lean startup startup twitter user experience business model canvas.',
  likes: 14,
  views: 38,
  title_pic: 'https://images.pexels.com/photos/930530/pexels-photo-930530.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'
  },
  

  {title: 'What Are Arrow Functions',
  author: 'Eric Lombardo',
  published: '01-18-2021',
  content: 'Creative marketing channels sales client partnership investor disruptive user experience metrics graphical user interface ramen. Network effects focus market creative assets direct mailing pivot holy grail deployment social proof iteration churn rate partnership. Conversion interaction design niche market. Series A financing business model canvas investor creative channels iteration supply chain bootstrapping infographic A/B testing partner network iPad value proposition innovator. Business plan entrepreneur gen-z social proof metrics. Strategy learning curve pitch. Learning curve iPhone niche market lean startup value proposition low hanging fruit funding entrepreneur stock. Value proposition burn rate responsive web design. Partnership strategy seed money validation alpha ownership non-disclosure agreement deployment. Graphical user interface research & development first mover advantage scrum project.

  Social proof churn rate business plan infographic MVP market. Alpha infographic stock termsheet scrum project release android learning curve iPad gen-z stealth. Channels holy grail leverage influencer android buyer disruptive iteration. Paradigm shift equity gamification sales. A/B testing analytics startup customer return on investment research & development. Lean startup technology return on investment hackathon social media interaction design freemium buyer seed round leverage client pitch facebook. Growth hacking virality early adopters MVP alpha. Network effects user experience freemium validation prototype startup incubator monetization buyer value proposition. Responsive web design value proposition bootstrapping stock startup influencer conversion hackathon accelerator. Marketing first mover advantage product management startup.
  
  Buzz business plan stock monetization ramen founders analytics creative vesting period. Beta burn rate product management hypotheses crowdsource startup technology value proposition angel investor focus series A financing marketing launch party direct mailing. Social media deployment client release strategy. Success churn rate niche market low hanging fruit graphical user interface innovator crowdfunding termsheet research & development android paradigm shift influencer pitch lean startup. Social media graphical user interface social proof infrastructure low hanging fruit hypotheses customer. Freemium crowdsource mass market ecosystem. Supply chain user experience paradigm shift crowdsource growth hacking business model canvas bandwidth pitch vesting period. Success seed money first mover advantage metrics hypotheses. Business-to-business stealth beta incubator gamification seed round partner network. MVP traction launch party virality release seed round monetization infographic rockstar lean startup startup twitter user experience business model canvas.',
  likes: 4,
  views: 23,
  title_pic: 'https://images.pexels.com/photos/930530/pexels-photo-930530.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'
  },

  {title: 'Building A Rails API Backend',
  author: 'Eric Lombardo',
  published: '04-10-2021',
  content: 'Creative marketing channels sales client partnership investor disruptive user experience metrics graphical user interface ramen. Network effects focus market creative assets direct mailing pivot holy grail deployment social proof iteration churn rate partnership. Conversion interaction design niche market. Series A financing business model canvas investor creative channels iteration supply chain bootstrapping infographic A/B testing partner network iPad value proposition innovator. Business plan entrepreneur gen-z social proof metrics. Strategy learning curve pitch. Learning curve iPhone niche market lean startup value proposition low hanging fruit funding entrepreneur stock. Value proposition burn rate responsive web design. Partnership strategy seed money validation alpha ownership non-disclosure agreement deployment. Graphical user interface research & development first mover advantage scrum project.

  Social proof churn rate business plan infographic MVP market. Alpha infographic stock termsheet scrum project release android learning curve iPad gen-z stealth. Channels holy grail leverage influencer android buyer disruptive iteration. Paradigm shift equity gamification sales. A/B testing analytics startup customer return on investment research & development. Lean startup technology return on investment hackathon social media interaction design freemium buyer seed round leverage client pitch facebook. Growth hacking virality early adopters MVP alpha. Network effects user experience freemium validation prototype startup incubator monetization buyer value proposition. Responsive web design value proposition bootstrapping stock startup influencer conversion hackathon accelerator. Marketing first mover advantage product management startup.
  
  Buzz business plan stock monetization ramen founders analytics creative vesting period. Beta burn rate product management hypotheses crowdsource startup technology value proposition angel investor focus series A financing marketing launch party direct mailing. Social media deployment client release strategy. Success churn rate niche market low hanging fruit graphical user interface innovator crowdfunding termsheet research & development android paradigm shift influencer pitch lean startup. Social media graphical user interface social proof infrastructure low hanging fruit hypotheses customer. Freemium crowdsource mass market ecosystem. Supply chain user experience paradigm shift crowdsource growth hacking business model canvas bandwidth pitch vesting period. Success seed money first mover advantage metrics hypotheses. Business-to-business stealth beta incubator gamification seed round partner network. MVP traction launch party virality release seed round monetization infographic rockstar lean startup startup twitter user experience business model canvas.',
  likes: 29,
  views: 401,
  title_pic: 'https://images.pexels.com/photos/930530/pexels-photo-930530.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'
  },

  {title: 'What To Look For In A Gem',
  author: 'Eric Lombardo',
  published: '02-28-2021',
  content: 'Creative marketing channels sales client partnership investor disruptive user experience metrics graphical user interface ramen. Network effects focus market creative assets direct mailing pivot holy grail deployment social proof iteration churn rate partnership. Conversion interaction design niche market. Series A financing business model canvas investor creative channels iteration supply chain bootstrapping infographic A/B testing partner network iPad value proposition innovator. Business plan entrepreneur gen-z social proof metrics. Strategy learning curve pitch. Learning curve iPhone niche market lean startup value proposition low hanging fruit funding entrepreneur stock. Value proposition burn rate responsive web design. Partnership strategy seed money validation alpha ownership non-disclosure agreement deployment. Graphical user interface research & development first mover advantage scrum project.

  Social proof churn rate business plan infographic MVP market. Alpha infographic stock termsheet scrum project release android learning curve iPad gen-z stealth. Channels holy grail leverage influencer android buyer disruptive iteration. Paradigm shift equity gamification sales. A/B testing analytics startup customer return on investment research & development. Lean startup technology return on investment hackathon social media interaction design freemium buyer seed round leverage client pitch facebook. Growth hacking virality early adopters MVP alpha. Network effects user experience freemium validation prototype startup incubator monetization buyer value proposition. Responsive web design value proposition bootstrapping stock startup influencer conversion hackathon accelerator. Marketing first mover advantage product management startup.
  
  Buzz business plan stock monetization ramen founders analytics creative vesting period. Beta burn rate product management hypotheses crowdsource startup technology value proposition angel investor focus series A financing marketing launch party direct mailing. Social media deployment client release strategy. Success churn rate niche market low hanging fruit graphical user interface innovator crowdfunding termsheet research & development android paradigm shift influencer pitch lean startup. Social media graphical user interface social proof infrastructure low hanging fruit hypotheses customer. Freemium crowdsource mass market ecosystem. Supply chain user experience paradigm shift crowdsource growth hacking business model canvas bandwidth pitch vesting period. Success seed money first mover advantage metrics hypotheses. Business-to-business stealth beta incubator gamification seed round partner network. MVP traction launch party virality release seed round monetization infographic rockstar lean startup startup twitter user experience business model canvas.',
  likes: 58,
  views: 1203,
  title_pic: 'https://images.pexels.com/photos/930530/pexels-photo-930530.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'
  },

  {title: 'Writing Arrow Functions',
  author: 'Eric Lombardo',
  published: '08-20-2020',
  content: 'Creative marketing channels sales client partnership investor disruptive user experience metrics graphical user interface ramen. Network effects focus market creative assets direct mailing pivot holy grail deployment social proof iteration churn rate partnership. Conversion interaction design niche market. Series A financing business model canvas investor creative channels iteration supply chain bootstrapping infographic A/B testing partner network iPad value proposition innovator. Business plan entrepreneur gen-z social proof metrics. Strategy learning curve pitch. Learning curve iPhone niche market lean startup value proposition low hanging fruit funding entrepreneur stock. Value proposition burn rate responsive web design. Partnership strategy seed money validation alpha ownership non-disclosure agreement deployment. Graphical user interface research & development first mover advantage scrum project.

  Social proof churn rate business plan infographic MVP market. Alpha infographic stock termsheet scrum project release android learning curve iPad gen-z stealth. Channels holy grail leverage influencer android buyer disruptive iteration. Paradigm shift equity gamification sales. A/B testing analytics startup customer return on investment research & development. Lean startup technology return on investment hackathon social media interaction design freemium buyer seed round leverage client pitch facebook. Growth hacking virality early adopters MVP alpha. Network effects user experience freemium validation prototype startup incubator monetization buyer value proposition. Responsive web design value proposition bootstrapping stock startup influencer conversion hackathon accelerator. Marketing first mover advantage product management startup.
  
  Buzz business plan stock monetization ramen founders analytics creative vesting period. Beta burn rate product management hypotheses crowdsource startup technology value proposition angel investor focus series A financing marketing launch party direct mailing. Social media deployment client release strategy. Success churn rate niche market low hanging fruit graphical user interface innovator crowdfunding termsheet research & development android paradigm shift influencer pitch lean startup. Social media graphical user interface social proof infrastructure low hanging fruit hypotheses customer. Freemium crowdsource mass market ecosystem. Supply chain user experience paradigm shift crowdsource growth hacking business model canvas bandwidth pitch vesting period. Success seed money first mover advantage metrics hypotheses. Business-to-business stealth beta incubator gamification seed round partner network. MVP traction launch party virality release seed round monetization infographic rockstar lean startup startup twitter user experience business model canvas.',
  likes: 80,
  views: 3432,
  title_pic: 'https://images.pexels.com/photos/930530/pexels-photo-930530.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'
  }
])

# comment bank
comment_list = ['This looks perfect. Just Photoshop out the dog, add a baby, and make the curtains blue concept is bang on, but can we look at a better execution try a more powerful colour. Doing some work for us "pro bono" will really add to your portfolio i promise what is lorem ipsum?', 'Can you put "find us on facebook" by the facebook logo? can you make the blue bluer? can you pimp this powerpoint, need more geometry patterns this is just a 5 minutes job. Just do what you think.', 'can you make it pop. Can you make the blue bluer? is there a way we can make the page feel more introductory without being cheesy for do less with more and the hair is just too polarising, so this red is too red so just do what you think. I trust you, nor this is just a 5 minutes job.', 'I know you have made thirty iterations but can we go back to the first one that was the best version can you make the logo bigger yes bigger bigger still the logo is too big, and make it pop that sandwich needs to be more playful.', 'I love it, but can you invert all colors?']

# create comment and link to a post
Post.all.each do |post|
  post.comments.create(likes: rand(100), content: comment_list[rand(comment_list.count)], like_pic: './src/img/icons/heart-thin.png', title_pic: 'https://images.pexels.com/photos/930530/pexels-photo-930530.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940')
end


